# Generated by Django 3.0.3 on 2020-03-03 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moduleID', models.CharField(max_length=5)),
                ('moduleName', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=5)),
                ('semester', models.CharField(max_length=1)),
                ('professorID', models.CharField(max_length=5)),
                ('professorName', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratingID', models.CharField(max_length=5)),
                ('userID', models.CharField(max_length=10)),
                ('moduleID', models.CharField(max_length=5)),
                ('year', models.CharField(max_length=5)),
                ('semester', models.CharField(max_length=1)),
                ('rating', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=10)),
                ('userName', models.CharField(max_length=35)),
                ('email', models.CharField(max_length=35)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
