# Generated by Django 3.0.3 on 2020-03-06 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0002_auto_20200306_1536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='userID',
            new_name='userName',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='ratingID',
        ),
    ]
