# Generated by Django 3.0.3 on 2020-03-06 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0003_auto_20200306_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='professorID',
            field=models.CharField(default='JE1', max_length=5),
        ),
    ]
